services:
  mysql:
    image: mysql:8.0
    container_name: golang_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - golang_mysql:/var/lib/mysql

volumes:
  golang_mysql:
